### ISSUE TITLE
Interface gera_html_botao.py, funcao subm_comprar: problemas

### ISSUE THREAD

**Issue by JorgeStolfi** [JorgeStolfi/Projeto-MC857-2019#11]
Problemas em gera_html_botao.py, funcao subm_comprar:
* **Não altere o repositório fora da aula**.
* Essa função deveria gerar apenas o botão \<input type="submit"\> "COMPRAR".  O \<form\>...\</form\> que contém esse botão é gerado por outra função, gera_html_form.comprar(prod)
* A função não deve deve receber a quantidade, pois é o usuário que preenche isso no formulário.  
* A função não deve receber parâmetros de estilo, pois eles devem ser padronizados para todos os botões na implementação.

**Comment by humanolaranja** [comment]
Corrigido em 9db06bf72d87ebc1aa61a5b7bd19e764fcb9d424
