### ISSUE TITLE
Pasta "html", "utils", funções gera_html_pag_IMP.login, gera_html_form.login: problemas

### ISSUE THREAD

**Issue by JorgeStolfi** [JorgeStolfi/Projeto-MC857-2019#16]
Problemas nas pastas "html", "utils" e nas funções `gera_html_pag_IMP.login`, `gera_html_form.login`:
* O miolo da página deve ser gerado pela função gera_html_form.login()
* A função `gera_html_form.login()` deve gerar o HTML diretamente, em vez de ler de um arquivo (mais eficiente, mais flexível, mais fácil de manter, etc.)
* As pastas "html" e "utils", e a componente "page_loader.py" devem ser eliminadas.

**Comment by LucianoFabris** [comment]
Consertado no commit 158a1535c5d8818634d44f0581f9651476bd73b9
