### ISSUE TITLE
base_produtos.py - problemas

### ISSUE THREAD

**Issue by JorgeStolfi** [JorgeStolfi/Projeto-MC857-2019#5]
Problemas na interface base_produtos.py :
* **Não mexa no repositório antes da aula**.
* Não se deve usar nomes de variáveis ou parâmetros iguais aos nomes
de módulos.  Assim, `produto` deve ser `prod`, etc.
* Os nomes das funções não precisam dizer `produto` porque isso já está no nome do módulo. A função `busca_produto_nome` deveria se chamar apenas `busca_por_nome`.  Idem para as outras.
* Os comentários devem ter sintaxe, maúsculas e pontuação corretas, no tempo indicativo presente ("Devolve" em vez de "Devolver", "Devolva", "Devolverá", etc.).  Variáveis e funções citadas nos comentários devem ser marcadas com "{}" para reduzir confusão.
* Os comentários devem descrever mais precisamente e detalhadamente o que a função faz.  Por exemplo, `busca_por_nome(usr)` deveria ser "Devolve uma lista Python de objetos da classe {Produto}, consistindo de todos os produtos da base que tem a cadeia {nome} no seu nome, em ordem arbitrária.  Se não houver nenhum produto que satisfaz essa busca, devolve {None}."
* As funções `busca_produto_tipo` e `busca_produto_preco` não faz  sentido. Podutos não tem "tipo", e nenhum cliente vai querer saber **todos** os produtos com preço entre R$10 e R$20.
* A função `busca_produto(produto)` não faz sentido.
* Falta uma função `conecta` que abre a base de dados armazenada no disco.

**Comment by guilhermeluisdomingues** [comment]
Issue resolvida no commit 56c4a58b87d3fb63e5d808ddba9328ef193cafaf
