### ISSUE TITLE
pedido.py - problemas

### ISSUE THREAD

**Issue by JorgeStolfi** [JorgeStolfi/Projeto-MC857-2019#8]
Problemas na interface pedido.py:
* **Não mexa no repositório antes da aula**.
+ O comentário inicial deve ser "Este módulo define a classe {Pedido}. Um objeto desta classe representa e descreve um pedido de compra de um ou mais produtos em diversas quantidades, feito por um cliente da loja, que pode estar em várias etapas de execução."
+ O módulo deve também dizer `import carrinho; from carrinho import Carrinho`.
+ O módulo deve também dizer `import usuario; from usuario import Usuario`.
+ Evite usar o mesmo nome para variáveis e módulos. O argumento do método `cria` deveria ser `carr` ou `c` ou algo assim, não `carrinho`
+ A classe `Pedido` deve ter um método `obtem_usuario(self) `que retorna um objeto de classe `Usuario`.
+ A classe `Pedido` deve ter um método `obtem_status(self)` que devolve um `string` codificando o estado do pedido: "incompleto", "pagando", "despachado", "entregue", etc.  A descrição do método deve listar os códigos possíveis e explicar seu significado.

**Comment by remmessias** [comment]
Problemas corrigidos no commit e2e2030
